// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cbm

import "strconv"

type ECtrType int8

const (
	ECtrTypeBorders                  ECtrType = 0
	ECtrTypeBuckets                  ECtrType = 1
	ECtrTypeBinarizedTargetMeanValue ECtrType = 2
	ECtrTypeFloatTargetMeanValue     ECtrType = 3
	ECtrTypeCounter                  ECtrType = 4
	ECtrTypeFeatureFreq              ECtrType = 5
)

var EnumNamesECtrType = map[ECtrType]string{
	ECtrTypeBorders:                  "Borders",
	ECtrTypeBuckets:                  "Buckets",
	ECtrTypeBinarizedTargetMeanValue: "BinarizedTargetMeanValue",
	ECtrTypeFloatTargetMeanValue:     "FloatTargetMeanValue",
	ECtrTypeCounter:                  "Counter",
	ECtrTypeFeatureFreq:              "FeatureFreq",
}

var EnumValuesECtrType = map[string]ECtrType{
	"Borders":                  ECtrTypeBorders,
	"Buckets":                  ECtrTypeBuckets,
	"BinarizedTargetMeanValue": ECtrTypeBinarizedTargetMeanValue,
	"FloatTargetMeanValue":     ECtrTypeFloatTargetMeanValue,
	"Counter":                  ECtrTypeCounter,
	"FeatureFreq":              ECtrTypeFeatureFreq,
}

func (v ECtrType) String() string {
	if s, ok := EnumNamesECtrType[v]; ok {
		return s
	}
	return "ECtrType(" + strconv.FormatInt(int64(v), 10) + ")"
}
