// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cbm

import "strconv"

type ENanValueTreatment int8

const (
	ENanValueTreatmentAsIs    ENanValueTreatment = 0
	ENanValueTreatmentAsFalse ENanValueTreatment = 1
	ENanValueTreatmentAsTrue  ENanValueTreatment = 2
)

var EnumNamesENanValueTreatment = map[ENanValueTreatment]string{
	ENanValueTreatmentAsIs:    "AsIs",
	ENanValueTreatmentAsFalse: "AsFalse",
	ENanValueTreatmentAsTrue:  "AsTrue",
}

var EnumValuesENanValueTreatment = map[string]ENanValueTreatment{
	"AsIs":    ENanValueTreatmentAsIs,
	"AsFalse": ENanValueTreatmentAsFalse,
	"AsTrue":  ENanValueTreatmentAsTrue,
}

func (v ENanValueTreatment) String() string {
	if s, ok := EnumNamesENanValueTreatment[v]; ok {
		return s
	}
	return "ENanValueTreatment(" + strconv.FormatInt(int64(v), 10) + ")"
}
