// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cbm

import "strconv"

type ESourceFeatureType int8

const (
	ESourceFeatureTypeText      ESourceFeatureType = 0
	ESourceFeatureTypeEmbedding ESourceFeatureType = 1
)

var EnumNamesESourceFeatureType = map[ESourceFeatureType]string{
	ESourceFeatureTypeText:      "Text",
	ESourceFeatureTypeEmbedding: "Embedding",
}

var EnumValuesESourceFeatureType = map[string]ESourceFeatureType{
	"Text":      ESourceFeatureTypeText,
	"Embedding": ESourceFeatureTypeEmbedding,
}

func (v ESourceFeatureType) String() string {
	if s, ok := EnumNamesESourceFeatureType[v]; ok {
		return s
	}
	return "ESourceFeatureType(" + strconv.FormatInt(int64(v), 10) + ")"
}
