// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cbm

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TCatFeature struct {
	_tab flatbuffers.Table
}

func GetRootAsTCatFeature(buf []byte, offset flatbuffers.UOffsetT) *TCatFeature {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TCatFeature{}
	x.Init(buf, n+offset)
	return x
}

func FinishTCatFeatureBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTCatFeature(buf []byte, offset flatbuffers.UOffsetT) *TCatFeature {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TCatFeature{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTCatFeatureBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TCatFeature) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TCatFeature) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TCatFeature) Index() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *TCatFeature) MutateIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *TCatFeature) FlatIndex() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *TCatFeature) MutateFlatIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *TCatFeature) FeatureId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TCatFeature) UsedInModel() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return true
}

func (rcv *TCatFeature) MutateUsedInModel(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func TCatFeatureStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func TCatFeatureAddIndex(builder *flatbuffers.Builder, index int32) {
	builder.PrependInt32Slot(0, index, -1)
}
func TCatFeatureAddFlatIndex(builder *flatbuffers.Builder, flatIndex int32) {
	builder.PrependInt32Slot(1, flatIndex, -1)
}
func TCatFeatureAddFeatureId(builder *flatbuffers.Builder, featureId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(featureId), 0)
}
func TCatFeatureAddUsedInModel(builder *flatbuffers.Builder, usedInModel bool) {
	builder.PrependBoolSlot(3, usedInModel, true)
}
func TCatFeatureEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
