// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cbm

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TCtrFeature struct {
	_tab flatbuffers.Table
}

func GetRootAsTCtrFeature(buf []byte, offset flatbuffers.UOffsetT) *TCtrFeature {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TCtrFeature{}
	x.Init(buf, n+offset)
	return x
}

func FinishTCtrFeatureBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTCtrFeature(buf []byte, offset flatbuffers.UOffsetT) *TCtrFeature {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TCtrFeature{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTCtrFeatureBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TCtrFeature) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TCtrFeature) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TCtrFeature) Ctr(obj *TModelCtr) *TModelCtr {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TModelCtr)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *TCtrFeature) Borders(j int) float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetFloat32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *TCtrFeature) BordersLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TCtrFeature) MutateBorders(j int, n float32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateFloat32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func TCtrFeatureStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TCtrFeatureAddCtr(builder *flatbuffers.Builder, ctr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(ctr), 0)
}
func TCtrFeatureAddBorders(builder *flatbuffers.Builder, borders flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(borders), 0)
}
func TCtrFeatureStartBordersVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TCtrFeatureEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
