// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cbm

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TCtrValueTable struct {
	_tab flatbuffers.Table
}

func GetRootAsTCtrValueTable(buf []byte, offset flatbuffers.UOffsetT) *TCtrValueTable {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TCtrValueTable{}
	x.Init(buf, n+offset)
	return x
}

func FinishTCtrValueTableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTCtrValueTable(buf []byte, offset flatbuffers.UOffsetT) *TCtrValueTable {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TCtrValueTable{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTCtrValueTableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TCtrValueTable) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TCtrValueTable) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TCtrValueTable) ModelCtrBase(obj *TModelCtrBase) *TModelCtrBase {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TModelCtrBase)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *TCtrValueTable) IndexHashRaw(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *TCtrValueTable) IndexHashRawLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TCtrValueTable) IndexHashRawBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TCtrValueTable) MutateIndexHashRaw(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *TCtrValueTable) Ctrblob(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *TCtrValueTable) CtrblobLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TCtrValueTable) CtrblobBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TCtrValueTable) MutateCtrblob(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *TCtrValueTable) CounterDenominator() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TCtrValueTable) MutateCounterDenominator(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *TCtrValueTable) TargetClassesCount() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TCtrValueTable) MutateTargetClassesCount(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func TCtrValueTableStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func TCtrValueTableAddModelCtrBase(builder *flatbuffers.Builder, modelCtrBase flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(modelCtrBase), 0)
}
func TCtrValueTableAddIndexHashRaw(builder *flatbuffers.Builder, indexHashRaw flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(indexHashRaw), 0)
}
func TCtrValueTableStartIndexHashRawVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func TCtrValueTableAddCtrblob(builder *flatbuffers.Builder, ctrblob flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(ctrblob), 0)
}
func TCtrValueTableStartCtrblobVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func TCtrValueTableAddCounterDenominator(builder *flatbuffers.Builder, counterDenominator int32) {
	builder.PrependInt32Slot(3, counterDenominator, 0)
}
func TCtrValueTableAddTargetClassesCount(builder *flatbuffers.Builder, targetClassesCount int32) {
	builder.PrependInt32Slot(4, targetClassesCount, 0)
}
func TCtrValueTableEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
