// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cbm

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TEmbeddingFeature struct {
	_tab flatbuffers.Table
}

func GetRootAsTEmbeddingFeature(buf []byte, offset flatbuffers.UOffsetT) *TEmbeddingFeature {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TEmbeddingFeature{}
	x.Init(buf, n+offset)
	return x
}

func FinishTEmbeddingFeatureBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTEmbeddingFeature(buf []byte, offset flatbuffers.UOffsetT) *TEmbeddingFeature {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TEmbeddingFeature{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTEmbeddingFeatureBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TEmbeddingFeature) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TEmbeddingFeature) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TEmbeddingFeature) Index() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *TEmbeddingFeature) MutateIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *TEmbeddingFeature) FlatIndex() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *TEmbeddingFeature) MutateFlatIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *TEmbeddingFeature) FeatureId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TEmbeddingFeature) Dimension() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TEmbeddingFeature) MutateDimension(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *TEmbeddingFeature) UsedInModel() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return true
}

func (rcv *TEmbeddingFeature) MutateUsedInModel(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func TEmbeddingFeatureStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func TEmbeddingFeatureAddIndex(builder *flatbuffers.Builder, index int32) {
	builder.PrependInt32Slot(0, index, -1)
}
func TEmbeddingFeatureAddFlatIndex(builder *flatbuffers.Builder, flatIndex int32) {
	builder.PrependInt32Slot(1, flatIndex, -1)
}
func TEmbeddingFeatureAddFeatureId(builder *flatbuffers.Builder, featureId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(featureId), 0)
}
func TEmbeddingFeatureAddDimension(builder *flatbuffers.Builder, dimension int32) {
	builder.PrependInt32Slot(3, dimension, 0)
}
func TEmbeddingFeatureAddUsedInModel(builder *flatbuffers.Builder, usedInModel bool) {
	builder.PrependBoolSlot(4, usedInModel, true)
}
func TEmbeddingFeatureEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
