// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cbm

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TEstimatedFeature struct {
	_tab flatbuffers.Table
}

func GetRootAsTEstimatedFeature(buf []byte, offset flatbuffers.UOffsetT) *TEstimatedFeature {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TEstimatedFeature{}
	x.Init(buf, n+offset)
	return x
}

func FinishTEstimatedFeatureBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTEstimatedFeature(buf []byte, offset flatbuffers.UOffsetT) *TEstimatedFeature {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TEstimatedFeature{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTEstimatedFeatureBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TEstimatedFeature) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TEstimatedFeature) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TEstimatedFeature) SourceFeatureIndex() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *TEstimatedFeature) MutateSourceFeatureIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *TEstimatedFeature) CalcerId(obj *TGuid) *TGuid {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(TGuid)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *TEstimatedFeature) LocalIndex() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *TEstimatedFeature) MutateLocalIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *TEstimatedFeature) Borders(j int) float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetFloat32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *TEstimatedFeature) BordersLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TEstimatedFeature) MutateBorders(j int, n float32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateFloat32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func (rcv *TEstimatedFeature) SourceFeatureType() ESourceFeatureType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return ESourceFeatureType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *TEstimatedFeature) MutateSourceFeatureType(n ESourceFeatureType) bool {
	return rcv._tab.MutateInt8Slot(12, int8(n))
}

func TEstimatedFeatureStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func TEstimatedFeatureAddSourceFeatureIndex(builder *flatbuffers.Builder, sourceFeatureIndex int32) {
	builder.PrependInt32Slot(0, sourceFeatureIndex, -1)
}
func TEstimatedFeatureAddCalcerId(builder *flatbuffers.Builder, calcerId flatbuffers.UOffsetT) {
	builder.PrependStructSlot(1, flatbuffers.UOffsetT(calcerId), 0)
}
func TEstimatedFeatureAddLocalIndex(builder *flatbuffers.Builder, localIndex int32) {
	builder.PrependInt32Slot(2, localIndex, -1)
}
func TEstimatedFeatureAddBorders(builder *flatbuffers.Builder, borders flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(borders), 0)
}
func TEstimatedFeatureStartBordersVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TEstimatedFeatureAddSourceFeatureType(builder *flatbuffers.Builder, sourceFeatureType ESourceFeatureType) {
	builder.PrependInt8Slot(4, int8(sourceFeatureType), 0)
}
func TEstimatedFeatureEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
