// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cbm

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TFloatSplit struct {
	_tab flatbuffers.Struct
}

func (rcv *TFloatSplit) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TFloatSplit) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *TFloatSplit) Index() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *TFloatSplit) MutateIndex(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *TFloatSplit) Border() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *TFloatSplit) MutateBorder(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func CreateTFloatSplit(builder *flatbuffers.Builder, index int32, border float32) flatbuffers.UOffsetT {
	builder.Prep(4, 8)
	builder.PrependFloat32(border)
	builder.PrependInt32(index)
	return builder.Offset()
}
