// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cbm

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TFloatFeature struct {
	_tab flatbuffers.Table
}

func GetRootAsTFloatFeature(buf []byte, offset flatbuffers.UOffsetT) *TFloatFeature {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TFloatFeature{}
	x.Init(buf, n+offset)
	return x
}

func FinishTFloatFeatureBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTFloatFeature(buf []byte, offset flatbuffers.UOffsetT) *TFloatFeature {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TFloatFeature{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTFloatFeatureBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TFloatFeature) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TFloatFeature) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TFloatFeature) HasNans() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TFloatFeature) MutateHasNans(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *TFloatFeature) Index() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *TFloatFeature) MutateIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *TFloatFeature) FlatIndex() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *TFloatFeature) MutateFlatIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *TFloatFeature) Borders(j int) float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetFloat32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *TFloatFeature) BordersLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TFloatFeature) MutateBorders(j int, n float32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateFloat32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func (rcv *TFloatFeature) FeatureId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TFloatFeature) NanValueTreatment() ENanValueTreatment {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return ENanValueTreatment(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *TFloatFeature) MutateNanValueTreatment(n ENanValueTreatment) bool {
	return rcv._tab.MutateInt8Slot(14, int8(n))
}

func TFloatFeatureStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func TFloatFeatureAddHasNans(builder *flatbuffers.Builder, hasNans bool) {
	builder.PrependBoolSlot(0, hasNans, false)
}
func TFloatFeatureAddIndex(builder *flatbuffers.Builder, index int32) {
	builder.PrependInt32Slot(1, index, -1)
}
func TFloatFeatureAddFlatIndex(builder *flatbuffers.Builder, flatIndex int32) {
	builder.PrependInt32Slot(2, flatIndex, -1)
}
func TFloatFeatureAddBorders(builder *flatbuffers.Builder, borders flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(borders), 0)
}
func TFloatFeatureStartBordersVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TFloatFeatureAddFeatureId(builder *flatbuffers.Builder, featureId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(featureId), 0)
}
func TFloatFeatureAddNanValueTreatment(builder *flatbuffers.Builder, nanValueTreatment ENanValueTreatment) {
	builder.PrependInt8Slot(5, int8(nanValueTreatment), 0)
}
func TFloatFeatureEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
