// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cbm

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TGuid struct {
	_tab flatbuffers.Struct
}

func (rcv *TGuid) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TGuid) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *TGuid) Dw0() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *TGuid) MutateDw0(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *TGuid) Dw1() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *TGuid) MutateDw1(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *TGuid) Dw2() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *TGuid) MutateDw2(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func (rcv *TGuid) Dw3() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(12))
}
func (rcv *TGuid) MutateDw3(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(12), n)
}

func CreateTGuid(builder *flatbuffers.Builder, dw0 uint32, dw1 uint32, dw2 uint32, dw3 uint32) flatbuffers.UOffsetT {
	builder.Prep(4, 16)
	builder.PrependUint32(dw3)
	builder.PrependUint32(dw2)
	builder.PrependUint32(dw1)
	builder.PrependUint32(dw0)
	return builder.Offset()
}
