// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cbm

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TModelCtr struct {
	_tab flatbuffers.Table
}

func GetRootAsTModelCtr(buf []byte, offset flatbuffers.UOffsetT) *TModelCtr {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TModelCtr{}
	x.Init(buf, n+offset)
	return x
}

func FinishTModelCtrBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTModelCtr(buf []byte, offset flatbuffers.UOffsetT) *TModelCtr {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TModelCtr{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTModelCtrBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TModelCtr) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TModelCtr) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TModelCtr) Base(obj *TModelCtrBase) *TModelCtrBase {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TModelCtrBase)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *TModelCtr) TargetBorderIdx() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TModelCtr) MutateTargetBorderIdx(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *TModelCtr) PriorNum() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *TModelCtr) MutatePriorNum(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *TModelCtr) PriorDenom() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 1.0
}

func (rcv *TModelCtr) MutatePriorDenom(n float32) bool {
	return rcv._tab.MutateFloat32Slot(10, n)
}

func (rcv *TModelCtr) Shift() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *TModelCtr) MutateShift(n float32) bool {
	return rcv._tab.MutateFloat32Slot(12, n)
}

func (rcv *TModelCtr) Scale() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 1.0
}

func (rcv *TModelCtr) MutateScale(n float32) bool {
	return rcv._tab.MutateFloat32Slot(14, n)
}

func TModelCtrStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func TModelCtrAddBase(builder *flatbuffers.Builder, base flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(base), 0)
}
func TModelCtrAddTargetBorderIdx(builder *flatbuffers.Builder, targetBorderIdx int32) {
	builder.PrependInt32Slot(1, targetBorderIdx, 0)
}
func TModelCtrAddPriorNum(builder *flatbuffers.Builder, priorNum float32) {
	builder.PrependFloat32Slot(2, priorNum, 0.0)
}
func TModelCtrAddPriorDenom(builder *flatbuffers.Builder, priorDenom float32) {
	builder.PrependFloat32Slot(3, priorDenom, 1.0)
}
func TModelCtrAddShift(builder *flatbuffers.Builder, shift float32) {
	builder.PrependFloat32Slot(4, shift, 0.0)
}
func TModelCtrAddScale(builder *flatbuffers.Builder, scale float32) {
	builder.PrependFloat32Slot(5, scale, 1.0)
}
func TModelCtrEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
