// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cbm

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TModelCtrBase struct {
	_tab flatbuffers.Table
}

func GetRootAsTModelCtrBase(buf []byte, offset flatbuffers.UOffsetT) *TModelCtrBase {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TModelCtrBase{}
	x.Init(buf, n+offset)
	return x
}

func FinishTModelCtrBaseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTModelCtrBase(buf []byte, offset flatbuffers.UOffsetT) *TModelCtrBase {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TModelCtrBase{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTModelCtrBaseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TModelCtrBase) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TModelCtrBase) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TModelCtrBase) FeatureCombination(obj *TFeatureCombination) *TFeatureCombination {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TFeatureCombination)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *TModelCtrBase) CtrType() ECtrType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return ECtrType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *TModelCtrBase) MutateCtrType(n ECtrType) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func (rcv *TModelCtrBase) TargetBorderClassifierIdx() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TModelCtrBase) MutateTargetBorderClassifierIdx(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func TModelCtrBaseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func TModelCtrBaseAddFeatureCombination(builder *flatbuffers.Builder, featureCombination flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(featureCombination), 0)
}
func TModelCtrBaseAddCtrType(builder *flatbuffers.Builder, ctrType ECtrType) {
	builder.PrependInt8Slot(1, int8(ctrType), 0)
}
func TModelCtrBaseAddTargetBorderClassifierIdx(builder *flatbuffers.Builder, targetBorderClassifierIdx int32) {
	builder.PrependInt32Slot(2, targetBorderClassifierIdx, 0)
}
func TModelCtrBaseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
