// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cbm

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TNonSymmetricTreeStepNode struct {
	_tab flatbuffers.Struct
}

func (rcv *TNonSymmetricTreeStepNode) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TNonSymmetricTreeStepNode) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *TNonSymmetricTreeStepNode) LeftSubtreeDiff() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *TNonSymmetricTreeStepNode) MutateLeftSubtreeDiff(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *TNonSymmetricTreeStepNode) RightSubtreeDiff() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(2))
}
func (rcv *TNonSymmetricTreeStepNode) MutateRightSubtreeDiff(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(2), n)
}

func CreateTNonSymmetricTreeStepNode(builder *flatbuffers.Builder, leftSubtreeDiff uint16, rightSubtreeDiff uint16) flatbuffers.UOffsetT {
	builder.Prep(2, 4)
	builder.PrependUint16(rightSubtreeDiff)
	builder.PrependUint16(leftSubtreeDiff)
	return builder.Offset()
}
