// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cbm

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TOneHotSplit struct {
	_tab flatbuffers.Struct
}

func (rcv *TOneHotSplit) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TOneHotSplit) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *TOneHotSplit) Index() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *TOneHotSplit) MutateIndex(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *TOneHotSplit) Value() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *TOneHotSplit) MutateValue(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func CreateTOneHotSplit(builder *flatbuffers.Builder, index int32, value int32) flatbuffers.UOffsetT {
	builder.Prep(4, 8)
	builder.PrependInt32(value)
	builder.PrependInt32(index)
	return builder.Offset()
}
