// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cbm

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TOneHotFeature struct {
	_tab flatbuffers.Table
}

func GetRootAsTOneHotFeature(buf []byte, offset flatbuffers.UOffsetT) *TOneHotFeature {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TOneHotFeature{}
	x.Init(buf, n+offset)
	return x
}

func FinishTOneHotFeatureBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTOneHotFeature(buf []byte, offset flatbuffers.UOffsetT) *TOneHotFeature {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TOneHotFeature{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTOneHotFeatureBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TOneHotFeature) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TOneHotFeature) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TOneHotFeature) Index() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *TOneHotFeature) MutateIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *TOneHotFeature) Values(j int) int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *TOneHotFeature) ValuesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TOneHotFeature) MutateValues(j int, n int32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func (rcv *TOneHotFeature) StringValues(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *TOneHotFeature) StringValuesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func TOneHotFeatureStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func TOneHotFeatureAddIndex(builder *flatbuffers.Builder, index int32) {
	builder.PrependInt32Slot(0, index, -1)
}
func TOneHotFeatureAddValues(builder *flatbuffers.Builder, values flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(values), 0)
}
func TOneHotFeatureStartValuesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TOneHotFeatureAddStringValues(builder *flatbuffers.Builder, stringValues flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(stringValues), 0)
}
func TOneHotFeatureStartStringValuesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TOneHotFeatureEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
