// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cbm

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TRepackedBin struct {
	_tab flatbuffers.Struct
}

func (rcv *TRepackedBin) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TRepackedBin) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *TRepackedBin) FeatureIndex() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *TRepackedBin) MutateFeatureIndex(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *TRepackedBin) XorMask() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(2))
}
func (rcv *TRepackedBin) MutateXorMask(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(2), n)
}

func (rcv *TRepackedBin) SplitIdx() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(3))
}
func (rcv *TRepackedBin) MutateSplitIdx(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(3), n)
}

func CreateTRepackedBin(builder *flatbuffers.Builder, featureIndex uint16, xorMask byte, splitIdx byte) flatbuffers.UOffsetT {
	builder.Prep(2, 4)
	builder.PrependByte(splitIdx)
	builder.PrependByte(xorMask)
	builder.PrependUint16(featureIndex)
	return builder.Offset()
}
