// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cbm

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TTextFeature struct {
	_tab flatbuffers.Table
}

func GetRootAsTTextFeature(buf []byte, offset flatbuffers.UOffsetT) *TTextFeature {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TTextFeature{}
	x.Init(buf, n+offset)
	return x
}

func FinishTTextFeatureBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTTextFeature(buf []byte, offset flatbuffers.UOffsetT) *TTextFeature {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TTextFeature{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTTextFeatureBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TTextFeature) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TTextFeature) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TTextFeature) Index() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *TTextFeature) MutateIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *TTextFeature) FlatIndex() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *TTextFeature) MutateFlatIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *TTextFeature) FeatureId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TTextFeature) UsedInModel() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return true
}

func (rcv *TTextFeature) MutateUsedInModel(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func TTextFeatureStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func TTextFeatureAddIndex(builder *flatbuffers.Builder, index int32) {
	builder.PrependInt32Slot(0, index, -1)
}
func TTextFeatureAddFlatIndex(builder *flatbuffers.Builder, flatIndex int32) {
	builder.PrependInt32Slot(1, flatIndex, -1)
}
func TTextFeatureAddFeatureId(builder *flatbuffers.Builder, featureId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(featureId), 0)
}
func TTextFeatureAddUsedInModel(builder *flatbuffers.Builder, usedInModel bool) {
	builder.PrependBoolSlot(3, usedInModel, true)
}
func TTextFeatureEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
